server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/daoyun?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=Asia/Shanghai
    username: root
    password: root
    hikari:
      pool-name: DataHikariCP
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-test-query: SELECT 1

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com/fzu/edu/daoyun/entity
  configuration:
    map-underscore-to-camel-case: false
logging:
  level:
    com.fzu.edu.daoyun.mapper: ERROR

jwt:
  tokenHeader: Authorization
  gitTokenHeader: gitToken
  secret: daoyun-secret
  expiration: 604800
  tokenHead: Bearer